### ISSUE TITLE
Remove already-published volumes from this repo

### ISSUE THREAD

**Issue by joewiz** [HistoryAtState/frus-not-yet-reviewed#1]
@vak2ve Could you please delete any volumes that've already been released? Thanks in advance! This will help for planning purposes.

**Comment by vak2ve** [comment]
@joewiz  frus-not-yet-reviewed cleaned up!

**Comment by joewiz** [comment]
@vak2ve Thanks, but I'm not seeing the commit at https://github.com/HistoryAtState/frus-not-yet-reviewed/commits/master. Could you try syncing again?

**Comment by joewiz** [comment]
@vak2ve Thank you!

Closed with https://github.com/HistoryAtState/frus-not-yet-reviewed/commit/aebb10282049a3779c9caef54351e86215d43f31.
